// Code generated by ent, DO NOT EDIT.

package accountcostconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountcostconfig type in the database.
	Label = "account_cost_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldCostType holds the string denoting the cost_type field in the database.
	FieldCostType = "cost_type"
	// FieldPeriodFee holds the string denoting the period_fee field in the database.
	FieldPeriodFee = "period_fee"
	// FieldPeriodDays holds the string denoting the period_days field in the database.
	FieldPeriodDays = "period_days"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldWindowBaselineRevenue holds the string denoting the window_baseline_revenue field in the database.
	FieldWindowBaselineRevenue = "window_baseline_revenue"
	// FieldAutoRenew holds the string denoting the auto_renew field in the database.
	FieldAutoRenew = "auto_renew"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// Table holds the table name of the accountcostconfig in the database.
	Table = "account_cost_configs"
)

// Columns holds all SQL columns for accountcostconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldCostType,
	FieldPeriodFee,
	FieldPeriodDays,
	FieldCurrency,
	FieldWindowBaselineRevenue,
	FieldAutoRenew,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCostType holds the default value on creation for the "cost_type" field.
	DefaultCostType string
	// CostTypeValidator is a validator for the "cost_type" field. It is called by the builders before save.
	CostTypeValidator func(string) error
	// DefaultPeriodFee holds the default value on creation for the "period_fee" field.
	DefaultPeriodFee float64
	// DefaultPeriodDays holds the default value on creation for the "period_days" field.
	DefaultPeriodDays int
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultAutoRenew holds the default value on creation for the "auto_renew" field.
	DefaultAutoRenew bool
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
)

// OrderOption defines the ordering options for the AccountCostConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByCostType orders the results by the cost_type field.
func ByCostType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostType, opts...).ToFunc()
}

// ByPeriodFee orders the results by the period_fee field.
func ByPeriodFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodFee, opts...).ToFunc()
}

// ByPeriodDays orders the results by the period_days field.
func ByPeriodDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodDays, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByWindowBaselineRevenue orders the results by the window_baseline_revenue field.
func ByWindowBaselineRevenue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowBaselineRevenue, opts...).ToFunc()
}

// ByAutoRenew orders the results by the auto_renew field.
func ByAutoRenew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoRenew, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}
