// Code generated by ent, DO NOT EDIT.

package accountcostconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAccountID, v))
}

// CostType applies equality check predicate on the "cost_type" field. It's identical to CostTypeEQ.
func CostType(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCostType, v))
}

// PeriodFee applies equality check predicate on the "period_fee" field. It's identical to PeriodFeeEQ.
func PeriodFee(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldPeriodFee, v))
}

// PeriodDays applies equality check predicate on the "period_days" field. It's identical to PeriodDaysEQ.
func PeriodDays(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldPeriodDays, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCurrency, v))
}

// WindowBaselineRevenue applies equality check predicate on the "window_baseline_revenue" field. It's identical to WindowBaselineRevenueEQ.
func WindowBaselineRevenue(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldWindowBaselineRevenue, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldAccountID, v))
}

// CostTypeEQ applies the EQ predicate on the "cost_type" field.
func CostTypeEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCostType, v))
}

// CostTypeNEQ applies the NEQ predicate on the "cost_type" field.
func CostTypeNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldCostType, v))
}

// CostTypeIn applies the In predicate on the "cost_type" field.
func CostTypeIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldCostType, vs...))
}

// CostTypeNotIn applies the NotIn predicate on the "cost_type" field.
func CostTypeNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldCostType, vs...))
}

// CostTypeGT applies the GT predicate on the "cost_type" field.
func CostTypeGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldCostType, v))
}

// CostTypeGTE applies the GTE predicate on the "cost_type" field.
func CostTypeGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldCostType, v))
}

// CostTypeLT applies the LT predicate on the "cost_type" field.
func CostTypeLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldCostType, v))
}

// CostTypeLTE applies the LTE predicate on the "cost_type" field.
func CostTypeLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldCostType, v))
}

// CostTypeContains applies the Contains predicate on the "cost_type" field.
func CostTypeContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldCostType, v))
}

// CostTypeHasPrefix applies the HasPrefix predicate on the "cost_type" field.
func CostTypeHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldCostType, v))
}

// CostTypeHasSuffix applies the HasSuffix predicate on the "cost_type" field.
func CostTypeHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldCostType, v))
}

// CostTypeEqualFold applies the EqualFold predicate on the "cost_type" field.
func CostTypeEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldCostType, v))
}

// CostTypeContainsFold applies the ContainsFold predicate on the "cost_type" field.
func CostTypeContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldCostType, v))
}

// PeriodFeeEQ applies the EQ predicate on the "period_fee" field.
func PeriodFeeEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldPeriodFee, v))
}

// PeriodFeeNEQ applies the NEQ predicate on the "period_fee" field.
func PeriodFeeNEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldPeriodFee, v))
}

// PeriodFeeIn applies the In predicate on the "period_fee" field.
func PeriodFeeIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldPeriodFee, vs...))
}

// PeriodFeeNotIn applies the NotIn predicate on the "period_fee" field.
func PeriodFeeNotIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldPeriodFee, vs...))
}

// PeriodFeeGT applies the GT predicate on the "period_fee" field.
func PeriodFeeGT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldPeriodFee, v))
}

// PeriodFeeGTE applies the GTE predicate on the "period_fee" field.
func PeriodFeeGTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldPeriodFee, v))
}

// PeriodFeeLT applies the LT predicate on the "period_fee" field.
func PeriodFeeLT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldPeriodFee, v))
}

// PeriodFeeLTE applies the LTE predicate on the "period_fee" field.
func PeriodFeeLTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldPeriodFee, v))
}

// PeriodDaysEQ applies the EQ predicate on the "period_days" field.
func PeriodDaysEQ(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldPeriodDays, v))
}

// PeriodDaysNEQ applies the NEQ predicate on the "period_days" field.
func PeriodDaysNEQ(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldPeriodDays, v))
}

// PeriodDaysIn applies the In predicate on the "period_days" field.
func PeriodDaysIn(vs ...int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldPeriodDays, vs...))
}

// PeriodDaysNotIn applies the NotIn predicate on the "period_days" field.
func PeriodDaysNotIn(vs ...int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldPeriodDays, vs...))
}

// PeriodDaysGT applies the GT predicate on the "period_days" field.
func PeriodDaysGT(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldPeriodDays, v))
}

// PeriodDaysGTE applies the GTE predicate on the "period_days" field.
func PeriodDaysGTE(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldPeriodDays, v))
}

// PeriodDaysLT applies the LT predicate on the "period_days" field.
func PeriodDaysLT(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldPeriodDays, v))
}

// PeriodDaysLTE applies the LTE predicate on the "period_days" field.
func PeriodDaysLTE(v int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldPeriodDays, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldCurrency, v))
}

// WindowBaselineRevenueEQ applies the EQ predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldWindowBaselineRevenue, v))
}

// WindowBaselineRevenueNEQ applies the NEQ predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueNEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldWindowBaselineRevenue, v))
}

// WindowBaselineRevenueIn applies the In predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldWindowBaselineRevenue, vs...))
}

// WindowBaselineRevenueNotIn applies the NotIn predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueNotIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldWindowBaselineRevenue, vs...))
}

// WindowBaselineRevenueGT applies the GT predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueGT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldWindowBaselineRevenue, v))
}

// WindowBaselineRevenueGTE applies the GTE predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueGTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldWindowBaselineRevenue, v))
}

// WindowBaselineRevenueLT applies the LT predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueLT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldWindowBaselineRevenue, v))
}

// WindowBaselineRevenueLTE applies the LTE predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueLTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldWindowBaselineRevenue, v))
}

// WindowBaselineRevenueIsNil applies the IsNil predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldWindowBaselineRevenue))
}

// WindowBaselineRevenueNotNil applies the NotNil predicate on the "window_baseline_revenue" field.
func WindowBaselineRevenueNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldWindowBaselineRevenue))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldNotes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountCostConfig) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountCostConfig) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountCostConfig) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.NotPredicates(p))
}
