// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountcostconfig"
)

// AccountCostConfig is the model entity for the AccountCostConfig schema.
type AccountCostConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// CostType holds the value of the "cost_type" field.
	CostType string `json:"cost_type,omitempty"`
	// PeriodFee holds the value of the "period_fee" field.
	PeriodFee float64 `json:"period_fee,omitempty"`
	// PeriodDays holds the value of the "period_days" field.
	PeriodDays int `json:"period_days,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// WindowBaselineRevenue holds the value of the "window_baseline_revenue" field.
	WindowBaselineRevenue *float64 `json:"window_baseline_revenue,omitempty"`
	// AutoRenew holds the value of the "auto_renew" field.
	AutoRenew bool `json:"auto_renew,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountCostConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountcostconfig.FieldAutoRenew:
			values[i] = new(sql.NullBool)
		case accountcostconfig.FieldPeriodFee, accountcostconfig.FieldWindowBaselineRevenue:
			values[i] = new(sql.NullFloat64)
		case accountcostconfig.FieldID, accountcostconfig.FieldAccountID, accountcostconfig.FieldPeriodDays:
			values[i] = new(sql.NullInt64)
		case accountcostconfig.FieldCostType, accountcostconfig.FieldCurrency, accountcostconfig.FieldNotes:
			values[i] = new(sql.NullString)
		case accountcostconfig.FieldCreatedAt, accountcostconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountCostConfig fields.
func (_m *AccountCostConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountcostconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountcostconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountcostconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountcostconfig.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountcostconfig.FieldCostType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cost_type", values[i])
			} else if value.Valid {
				_m.CostType = value.String
			}
		case accountcostconfig.FieldPeriodFee:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field period_fee", values[i])
			} else if value.Valid {
				_m.PeriodFee = value.Float64
			}
		case accountcostconfig.FieldPeriodDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field period_days", values[i])
			} else if value.Valid {
				_m.PeriodDays = int(value.Int64)
			}
		case accountcostconfig.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case accountcostconfig.FieldWindowBaselineRevenue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field window_baseline_revenue", values[i])
			} else if value.Valid {
				_m.WindowBaselineRevenue = new(float64)
				*_m.WindowBaselineRevenue = value.Float64
			}
		case accountcostconfig.FieldAutoRenew:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_renew", values[i])
			} else if value.Valid {
				_m.AutoRenew = value.Bool
			}
		case accountcostconfig.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountCostConfig.
// This includes values selected through modifiers, order, etc.
func (_m *AccountCostConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountCostConfig.
// Note that you need to call AccountCostConfig.Unwrap() before calling this method if this AccountCostConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountCostConfig) Update() *AccountCostConfigUpdateOne {
	return NewAccountCostConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountCostConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountCostConfig) Unwrap() *AccountCostConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountCostConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountCostConfig) String() string {
	var builder strings.Builder
	builder.WriteString("AccountCostConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("cost_type=")
	builder.WriteString(_m.CostType)
	builder.WriteString(", ")
	builder.WriteString("period_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeriodFee))
	builder.WriteString(", ")
	builder.WriteString("period_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeriodDays))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	if v := _m.WindowBaselineRevenue; v != nil {
		builder.WriteString("window_baseline_revenue=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("auto_renew=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoRenew))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// AccountCostConfigs is a parsable slice of AccountCostConfig.
type AccountCostConfigs []*AccountCostConfig
