// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcostconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCostConfigUpdate is the builder for updating AccountCostConfig entities.
type AccountCostConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AccountCostConfigMutation
}

// Where appends a list predicates to the AccountCostConfigUpdate builder.
func (_u *AccountCostConfigUpdate) Where(ps ...predicate.AccountCostConfig) *AccountCostConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountCostConfigUpdate) SetUpdatedAt(v time.Time) *AccountCostConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCostConfigUpdate) SetAccountID(v int64) *AccountCostConfigUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillableAccountID(v *int64) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCostConfigUpdate) AddAccountID(v int64) *AccountCostConfigUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetCostType sets the "cost_type" field.
func (_u *AccountCostConfigUpdate) SetCostType(v string) *AccountCostConfigUpdate {
	_u.mutation.SetCostType(v)
	return _u
}

// SetNillableCostType sets the "cost_type" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillableCostType(v *string) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetCostType(*v)
	}
	return _u
}

// SetPeriodFee sets the "period_fee" field.
func (_u *AccountCostConfigUpdate) SetPeriodFee(v float64) *AccountCostConfigUpdate {
	_u.mutation.ResetPeriodFee()
	_u.mutation.SetPeriodFee(v)
	return _u
}

// SetNillablePeriodFee sets the "period_fee" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillablePeriodFee(v *float64) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetPeriodFee(*v)
	}
	return _u
}

// AddPeriodFee adds value to the "period_fee" field.
func (_u *AccountCostConfigUpdate) AddPeriodFee(v float64) *AccountCostConfigUpdate {
	_u.mutation.AddPeriodFee(v)
	return _u
}

// SetPeriodDays sets the "period_days" field.
func (_u *AccountCostConfigUpdate) SetPeriodDays(v int) *AccountCostConfigUpdate {
	_u.mutation.ResetPeriodDays()
	_u.mutation.SetPeriodDays(v)
	return _u
}

// SetNillablePeriodDays sets the "period_days" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillablePeriodDays(v *int) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetPeriodDays(*v)
	}
	return _u
}

// AddPeriodDays adds value to the "period_days" field.
func (_u *AccountCostConfigUpdate) AddPeriodDays(v int) *AccountCostConfigUpdate {
	_u.mutation.AddPeriodDays(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AccountCostConfigUpdate) SetCurrency(v string) *AccountCostConfigUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillableCurrency(v *string) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetWindowBaselineRevenue sets the "window_baseline_revenue" field.
func (_u *AccountCostConfigUpdate) SetWindowBaselineRevenue(v float64) *AccountCostConfigUpdate {
	_u.mutation.ResetWindowBaselineRevenue()
	_u.mutation.SetWindowBaselineRevenue(v)
	return _u
}

// SetNillableWindowBaselineRevenue sets the "window_baseline_revenue" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillableWindowBaselineRevenue(v *float64) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetWindowBaselineRevenue(*v)
	}
	return _u
}

// AddWindowBaselineRevenue adds value to the "window_baseline_revenue" field.
func (_u *AccountCostConfigUpdate) AddWindowBaselineRevenue(v float64) *AccountCostConfigUpdate {
	_u.mutation.AddWindowBaselineRevenue(v)
	return _u
}

// ClearWindowBaselineRevenue clears the value of the "window_baseline_revenue" field.
func (_u *AccountCostConfigUpdate) ClearWindowBaselineRevenue() *AccountCostConfigUpdate {
	_u.mutation.ClearWindowBaselineRevenue()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AccountCostConfigUpdate) SetNotes(v string) *AccountCostConfigUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AccountCostConfigUpdate) SetNillableNotes(v *string) *AccountCostConfigUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AccountCostConfigUpdate) ClearNotes() *AccountCostConfigUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the AccountCostConfigMutation object of the builder.
func (_u *AccountCostConfigUpdate) Mutation() *AccountCostConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountCostConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCostConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountCostConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCostConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountCostConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountcostconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountCostConfigUpdate) check() error {
	if v, ok := _u.mutation.CostType(); ok {
		if err := accountcostconfig.CostTypeValidator(v); err != nil {
			return &ValidationError{Name: "cost_type", err: fmt.Errorf(`ent: validator failed for field "AccountCostConfig.cost_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := accountcostconfig.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "AccountCostConfig.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountCostConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountcostconfig.Table, accountcostconfig.Columns, sqlgraph.NewFieldSpec(accountcostconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcostconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcostconfig.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcostconfig.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostType(); ok {
		_spec.SetField(accountcostconfig.FieldCostType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodFee(); ok {
		_spec.SetField(accountcostconfig.FieldPeriodFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeriodFee(); ok {
		_spec.AddField(accountcostconfig.FieldPeriodFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PeriodDays(); ok {
		_spec.SetField(accountcostconfig.FieldPeriodDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeriodDays(); ok {
		_spec.AddField(accountcostconfig.FieldPeriodDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(accountcostconfig.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowBaselineRevenue(); ok {
		_spec.SetField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWindowBaselineRevenue(); ok {
		_spec.AddField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.WindowBaselineRevenueCleared() {
		_spec.ClearField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(accountcostconfig.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(accountcostconfig.FieldNotes, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcostconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountCostConfigUpdateOne is the builder for updating a single AccountCostConfig entity.
type AccountCostConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountCostConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountCostConfigUpdateOne) SetUpdatedAt(v time.Time) *AccountCostConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCostConfigUpdateOne) SetAccountID(v int64) *AccountCostConfigUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillableAccountID(v *int64) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCostConfigUpdateOne) AddAccountID(v int64) *AccountCostConfigUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetCostType sets the "cost_type" field.
func (_u *AccountCostConfigUpdateOne) SetCostType(v string) *AccountCostConfigUpdateOne {
	_u.mutation.SetCostType(v)
	return _u
}

// SetNillableCostType sets the "cost_type" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillableCostType(v *string) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetCostType(*v)
	}
	return _u
}

// SetPeriodFee sets the "period_fee" field.
func (_u *AccountCostConfigUpdateOne) SetPeriodFee(v float64) *AccountCostConfigUpdateOne {
	_u.mutation.ResetPeriodFee()
	_u.mutation.SetPeriodFee(v)
	return _u
}

// SetNillablePeriodFee sets the "period_fee" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillablePeriodFee(v *float64) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetPeriodFee(*v)
	}
	return _u
}

// AddPeriodFee adds value to the "period_fee" field.
func (_u *AccountCostConfigUpdateOne) AddPeriodFee(v float64) *AccountCostConfigUpdateOne {
	_u.mutation.AddPeriodFee(v)
	return _u
}

// SetPeriodDays sets the "period_days" field.
func (_u *AccountCostConfigUpdateOne) SetPeriodDays(v int) *AccountCostConfigUpdateOne {
	_u.mutation.ResetPeriodDays()
	_u.mutation.SetPeriodDays(v)
	return _u
}

// SetNillablePeriodDays sets the "period_days" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillablePeriodDays(v *int) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetPeriodDays(*v)
	}
	return _u
}

// AddPeriodDays adds value to the "period_days" field.
func (_u *AccountCostConfigUpdateOne) AddPeriodDays(v int) *AccountCostConfigUpdateOne {
	_u.mutation.AddPeriodDays(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AccountCostConfigUpdateOne) SetCurrency(v string) *AccountCostConfigUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillableCurrency(v *string) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetWindowBaselineRevenue sets the "window_baseline_revenue" field.
func (_u *AccountCostConfigUpdateOne) SetWindowBaselineRevenue(v float64) *AccountCostConfigUpdateOne {
	_u.mutation.ResetWindowBaselineRevenue()
	_u.mutation.SetWindowBaselineRevenue(v)
	return _u
}

// SetNillableWindowBaselineRevenue sets the "window_baseline_revenue" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillableWindowBaselineRevenue(v *float64) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetWindowBaselineRevenue(*v)
	}
	return _u
}

// AddWindowBaselineRevenue adds value to the "window_baseline_revenue" field.
func (_u *AccountCostConfigUpdateOne) AddWindowBaselineRevenue(v float64) *AccountCostConfigUpdateOne {
	_u.mutation.AddWindowBaselineRevenue(v)
	return _u
}

// ClearWindowBaselineRevenue clears the value of the "window_baseline_revenue" field.
func (_u *AccountCostConfigUpdateOne) ClearWindowBaselineRevenue() *AccountCostConfigUpdateOne {
	_u.mutation.ClearWindowBaselineRevenue()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AccountCostConfigUpdateOne) SetNotes(v string) *AccountCostConfigUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AccountCostConfigUpdateOne) SetNillableNotes(v *string) *AccountCostConfigUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AccountCostConfigUpdateOne) ClearNotes() *AccountCostConfigUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the AccountCostConfigMutation object of the builder.
func (_u *AccountCostConfigUpdateOne) Mutation() *AccountCostConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountCostConfigUpdate builder.
func (_u *AccountCostConfigUpdateOne) Where(ps ...predicate.AccountCostConfig) *AccountCostConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountCostConfigUpdateOne) Select(field string, fields ...string) *AccountCostConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountCostConfig entity.
func (_u *AccountCostConfigUpdateOne) Save(ctx context.Context) (*AccountCostConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCostConfigUpdateOne) SaveX(ctx context.Context) *AccountCostConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountCostConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCostConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountCostConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountcostconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountCostConfigUpdateOne) check() error {
	if v, ok := _u.mutation.CostType(); ok {
		if err := accountcostconfig.CostTypeValidator(v); err != nil {
			return &ValidationError{Name: "cost_type", err: fmt.Errorf(`ent: validator failed for field "AccountCostConfig.cost_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := accountcostconfig.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "AccountCostConfig.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountCostConfigUpdateOne) sqlSave(ctx context.Context) (_node *AccountCostConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountcostconfig.Table, accountcostconfig.Columns, sqlgraph.NewFieldSpec(accountcostconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountCostConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountcostconfig.FieldID)
		for _, f := range fields {
			if !accountcostconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountcostconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcostconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcostconfig.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcostconfig.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostType(); ok {
		_spec.SetField(accountcostconfig.FieldCostType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodFee(); ok {
		_spec.SetField(accountcostconfig.FieldPeriodFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeriodFee(); ok {
		_spec.AddField(accountcostconfig.FieldPeriodFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PeriodDays(); ok {
		_spec.SetField(accountcostconfig.FieldPeriodDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeriodDays(); ok {
		_spec.AddField(accountcostconfig.FieldPeriodDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(accountcostconfig.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowBaselineRevenue(); ok {
		_spec.SetField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWindowBaselineRevenue(); ok {
		_spec.AddField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.WindowBaselineRevenueCleared() {
		_spec.ClearField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(accountcostconfig.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(accountcostconfig.FieldNotes, field.TypeString)
	}
	_node = &AccountCostConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcostconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
