// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcostconfig"
)

// AccountCostConfigCreate is the builder for creating a AccountCostConfig entity.
type AccountCostConfigCreate struct {
	config
	mutation *AccountCostConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCostConfigCreate) SetCreatedAt(v time.Time) *AccountCostConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillableCreatedAt(v *time.Time) *AccountCostConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCostConfigCreate) SetUpdatedAt(v time.Time) *AccountCostConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillableUpdatedAt(v *time.Time) *AccountCostConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountCostConfigCreate) SetAccountID(v int64) *AccountCostConfigCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetCostType sets the "cost_type" field.
func (_c *AccountCostConfigCreate) SetCostType(v string) *AccountCostConfigCreate {
	_c.mutation.SetCostType(v)
	return _c
}

// SetNillableCostType sets the "cost_type" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillableCostType(v *string) *AccountCostConfigCreate {
	if v != nil {
		_c.SetCostType(*v)
	}
	return _c
}

// SetPeriodFee sets the "period_fee" field.
func (_c *AccountCostConfigCreate) SetPeriodFee(v float64) *AccountCostConfigCreate {
	_c.mutation.SetPeriodFee(v)
	return _c
}

// SetNillablePeriodFee sets the "period_fee" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillablePeriodFee(v *float64) *AccountCostConfigCreate {
	if v != nil {
		_c.SetPeriodFee(*v)
	}
	return _c
}

// SetPeriodDays sets the "period_days" field.
func (_c *AccountCostConfigCreate) SetPeriodDays(v int) *AccountCostConfigCreate {
	_c.mutation.SetPeriodDays(v)
	return _c
}

// SetNillablePeriodDays sets the "period_days" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillablePeriodDays(v *int) *AccountCostConfigCreate {
	if v != nil {
		_c.SetPeriodDays(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *AccountCostConfigCreate) SetCurrency(v string) *AccountCostConfigCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillableCurrency(v *string) *AccountCostConfigCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetWindowBaselineRevenue sets the "window_baseline_revenue" field.
func (_c *AccountCostConfigCreate) SetWindowBaselineRevenue(v float64) *AccountCostConfigCreate {
	_c.mutation.SetWindowBaselineRevenue(v)
	return _c
}

// SetNillableWindowBaselineRevenue sets the "window_baseline_revenue" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillableWindowBaselineRevenue(v *float64) *AccountCostConfigCreate {
	if v != nil {
		_c.SetWindowBaselineRevenue(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *AccountCostConfigCreate) SetNotes(v string) *AccountCostConfigCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *AccountCostConfigCreate) SetNillableNotes(v *string) *AccountCostConfigCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// Mutation returns the AccountCostConfigMutation object of the builder.
func (_c *AccountCostConfigCreate) Mutation() *AccountCostConfigMutation {
	return _c.mutation
}

// Save creates the AccountCostConfig in the database.
func (_c *AccountCostConfigCreate) Save(ctx context.Context) (*AccountCostConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCostConfigCreate) SaveX(ctx context.Context) *AccountCostConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCostConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCostConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCostConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountcostconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountcostconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CostType(); !ok {
		v := accountcostconfig.DefaultCostType
		_c.mutation.SetCostType(v)
	}
	if _, ok := _c.mutation.PeriodFee(); !ok {
		v := accountcostconfig.DefaultPeriodFee
		_c.mutation.SetPeriodFee(v)
	}
	if _, ok := _c.mutation.PeriodDays(); !ok {
		v := accountcostconfig.DefaultPeriodDays
		_c.mutation.SetPeriodDays(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := accountcostconfig.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := accountcostconfig.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCostConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountCostConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountCostConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountCostConfig.account_id"`)}
	}
	if _, ok := _c.mutation.CostType(); !ok {
		return &ValidationError{Name: "cost_type", err: errors.New(`ent: missing required field "AccountCostConfig.cost_type"`)}
	}
	if v, ok := _c.mutation.CostType(); ok {
		if err := accountcostconfig.CostTypeValidator(v); err != nil {
			return &ValidationError{Name: "cost_type", err: fmt.Errorf(`ent: validator failed for field "AccountCostConfig.cost_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeriodFee(); !ok {
		return &ValidationError{Name: "period_fee", err: errors.New(`ent: missing required field "AccountCostConfig.period_fee"`)}
	}
	if _, ok := _c.mutation.PeriodDays(); !ok {
		return &ValidationError{Name: "period_days", err: errors.New(`ent: missing required field "AccountCostConfig.period_days"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "AccountCostConfig.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := accountcostconfig.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "AccountCostConfig.currency": %w`, err)}
		}
	}
	return nil
}

func (_c *AccountCostConfigCreate) sqlSave(ctx context.Context) (*AccountCostConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCostConfigCreate) createSpec() (*AccountCostConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountCostConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountcostconfig.Table, sqlgraph.NewFieldSpec(accountcostconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountcostconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcostconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountcostconfig.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.CostType(); ok {
		_spec.SetField(accountcostconfig.FieldCostType, field.TypeString, value)
		_node.CostType = value
	}
	if value, ok := _c.mutation.PeriodFee(); ok {
		_spec.SetField(accountcostconfig.FieldPeriodFee, field.TypeFloat64, value)
		_node.PeriodFee = value
	}
	if value, ok := _c.mutation.PeriodDays(); ok {
		_spec.SetField(accountcostconfig.FieldPeriodDays, field.TypeInt, value)
		_node.PeriodDays = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(accountcostconfig.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.WindowBaselineRevenue(); ok {
		_spec.SetField(accountcostconfig.FieldWindowBaselineRevenue, field.TypeFloat64, value)
		_node.WindowBaselineRevenue = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(accountcostconfig.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountCostConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountCostConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCostConfigCreate) OnConflict(opts ...sql.ConflictOption) *AccountCostConfigUpsertOne {
	_c.conflict = opts
	return &AccountCostConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountCostConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCostConfigCreate) OnConflictColumns(columns ...string) *AccountCostConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountCostConfigUpsertOne{
		create: _c,
	}
}

type (
	// AccountCostConfigUpsertOne is the builder for "upsert"-ing
	//  one AccountCostConfig node.
	AccountCostConfigUpsertOne struct {
		create *AccountCostConfigCreate
	}

	// AccountCostConfigUpsert is the "OnConflict" setter.
	AccountCostConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountCostConfigUpsert) SetUpdatedAt(v time.Time) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdateUpdatedAt() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountCostConfigUpsert) SetAccountID(v int64) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdateAccountID() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCostConfigUpsert) AddAccountID(v int64) *AccountCostConfigUpsert {
	u.Add(accountcostconfig.FieldAccountID, v)
	return u
}

// SetCostType sets the "cost_type" field.
func (u *AccountCostConfigUpsert) SetCostType(v string) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldCostType, v)
	return u
}

// UpdateCostType sets the "cost_type" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdateCostType() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldCostType)
	return u
}

// SetPeriodFee sets the "period_fee" field.
func (u *AccountCostConfigUpsert) SetPeriodFee(v float64) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldPeriodFee, v)
	return u
}

// UpdatePeriodFee sets the "period_fee" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdatePeriodFee() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldPeriodFee)
	return u
}

// AddPeriodFee adds v to the "period_fee" field.
func (u *AccountCostConfigUpsert) AddPeriodFee(v float64) *AccountCostConfigUpsert {
	u.Add(accountcostconfig.FieldPeriodFee, v)
	return u
}

// SetPeriodDays sets the "period_days" field.
func (u *AccountCostConfigUpsert) SetPeriodDays(v int) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldPeriodDays, v)
	return u
}

// UpdatePeriodDays sets the "period_days" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdatePeriodDays() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldPeriodDays)
	return u
}

// AddPeriodDays adds v to the "period_days" field.
func (u *AccountCostConfigUpsert) AddPeriodDays(v int) *AccountCostConfigUpsert {
	u.Add(accountcostconfig.FieldPeriodDays, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *AccountCostConfigUpsert) SetCurrency(v string) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdateCurrency() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldCurrency)
	return u
}

// SetWindowBaselineRevenue sets the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsert) SetWindowBaselineRevenue(v float64) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldWindowBaselineRevenue, v)
	return u
}

// UpdateWindowBaselineRevenue sets the "window_baseline_revenue" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdateWindowBaselineRevenue() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldWindowBaselineRevenue)
	return u
}

// AddWindowBaselineRevenue adds v to the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsert) AddWindowBaselineRevenue(v float64) *AccountCostConfigUpsert {
	u.Add(accountcostconfig.FieldWindowBaselineRevenue, v)
	return u
}

// ClearWindowBaselineRevenue clears the value of the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsert) ClearWindowBaselineRevenue() *AccountCostConfigUpsert {
	u.SetNull(accountcostconfig.FieldWindowBaselineRevenue)
	return u
}

// SetNotes sets the "notes" field.
func (u *AccountCostConfigUpsert) SetNotes(v string) *AccountCostConfigUpsert {
	u.Set(accountcostconfig.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AccountCostConfigUpsert) UpdateNotes() *AccountCostConfigUpsert {
	u.SetExcluded(accountcostconfig.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *AccountCostConfigUpsert) ClearNotes() *AccountCostConfigUpsert {
	u.SetNull(accountcostconfig.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountCostConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountCostConfigUpsertOne) UpdateNewValues() *AccountCostConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountcostconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountCostConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountCostConfigUpsertOne) Ignore() *AccountCostConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountCostConfigUpsertOne) DoNothing() *AccountCostConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCostConfigCreate.OnConflict
// documentation for more info.
func (u *AccountCostConfigUpsertOne) Update(set func(*AccountCostConfigUpsert)) *AccountCostConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountCostConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountCostConfigUpsertOne) SetUpdatedAt(v time.Time) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdateUpdatedAt() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountCostConfigUpsertOne) SetAccountID(v int64) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCostConfigUpsertOne) AddAccountID(v int64) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdateAccountID() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateAccountID()
	})
}

// SetCostType sets the "cost_type" field.
func (u *AccountCostConfigUpsertOne) SetCostType(v string) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetCostType(v)
	})
}

// UpdateCostType sets the "cost_type" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdateCostType() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateCostType()
	})
}

// SetPeriodFee sets the "period_fee" field.
func (u *AccountCostConfigUpsertOne) SetPeriodFee(v float64) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetPeriodFee(v)
	})
}

// AddPeriodFee adds v to the "period_fee" field.
func (u *AccountCostConfigUpsertOne) AddPeriodFee(v float64) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddPeriodFee(v)
	})
}

// UpdatePeriodFee sets the "period_fee" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdatePeriodFee() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdatePeriodFee()
	})
}

// SetPeriodDays sets the "period_days" field.
func (u *AccountCostConfigUpsertOne) SetPeriodDays(v int) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetPeriodDays(v)
	})
}

// AddPeriodDays adds v to the "period_days" field.
func (u *AccountCostConfigUpsertOne) AddPeriodDays(v int) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddPeriodDays(v)
	})
}

// UpdatePeriodDays sets the "period_days" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdatePeriodDays() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdatePeriodDays()
	})
}

// SetCurrency sets the "currency" field.
func (u *AccountCostConfigUpsertOne) SetCurrency(v string) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdateCurrency() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateCurrency()
	})
}

// SetWindowBaselineRevenue sets the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsertOne) SetWindowBaselineRevenue(v float64) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetWindowBaselineRevenue(v)
	})
}

// AddWindowBaselineRevenue adds v to the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsertOne) AddWindowBaselineRevenue(v float64) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddWindowBaselineRevenue(v)
	})
}

// UpdateWindowBaselineRevenue sets the "window_baseline_revenue" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdateWindowBaselineRevenue() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateWindowBaselineRevenue()
	})
}

// ClearWindowBaselineRevenue clears the value of the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsertOne) ClearWindowBaselineRevenue() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.ClearWindowBaselineRevenue()
	})
}

// SetNotes sets the "notes" field.
func (u *AccountCostConfigUpsertOne) SetNotes(v string) *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AccountCostConfigUpsertOne) UpdateNotes() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AccountCostConfigUpsertOne) ClearNotes() *AccountCostConfigUpsertOne {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *AccountCostConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCostConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountCostConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountCostConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountCostConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCostConfigCreateBulk is the builder for creating many AccountCostConfig entities in bulk.
type AccountCostConfigCreateBulk struct {
	config
	err      error
	builders []*AccountCostConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountCostConfig entities in the database.
func (_c *AccountCostConfigCreateBulk) Save(ctx context.Context) ([]*AccountCostConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountCostConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountCostConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCostConfigCreateBulk) SaveX(ctx context.Context) []*AccountCostConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCostConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCostConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountCostConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountCostConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCostConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountCostConfigUpsertBulk {
	_c.conflict = opts
	return &AccountCostConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountCostConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCostConfigCreateBulk) OnConflictColumns(columns ...string) *AccountCostConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountCostConfigUpsertBulk{
		create: _c,
	}
}

// AccountCostConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountCostConfig nodes.
type AccountCostConfigUpsertBulk struct {
	create *AccountCostConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountCostConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountCostConfigUpsertBulk) UpdateNewValues() *AccountCostConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountcostconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountCostConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountCostConfigUpsertBulk) Ignore() *AccountCostConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountCostConfigUpsertBulk) DoNothing() *AccountCostConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCostConfigCreateBulk.OnConflict
// documentation for more info.
func (u *AccountCostConfigUpsertBulk) Update(set func(*AccountCostConfigUpsert)) *AccountCostConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountCostConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountCostConfigUpsertBulk) SetUpdatedAt(v time.Time) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdateUpdatedAt() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountCostConfigUpsertBulk) SetAccountID(v int64) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCostConfigUpsertBulk) AddAccountID(v int64) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdateAccountID() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateAccountID()
	})
}

// SetCostType sets the "cost_type" field.
func (u *AccountCostConfigUpsertBulk) SetCostType(v string) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetCostType(v)
	})
}

// UpdateCostType sets the "cost_type" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdateCostType() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateCostType()
	})
}

// SetPeriodFee sets the "period_fee" field.
func (u *AccountCostConfigUpsertBulk) SetPeriodFee(v float64) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetPeriodFee(v)
	})
}

// AddPeriodFee adds v to the "period_fee" field.
func (u *AccountCostConfigUpsertBulk) AddPeriodFee(v float64) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddPeriodFee(v)
	})
}

// UpdatePeriodFee sets the "period_fee" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdatePeriodFee() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdatePeriodFee()
	})
}

// SetPeriodDays sets the "period_days" field.
func (u *AccountCostConfigUpsertBulk) SetPeriodDays(v int) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetPeriodDays(v)
	})
}

// AddPeriodDays adds v to the "period_days" field.
func (u *AccountCostConfigUpsertBulk) AddPeriodDays(v int) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddPeriodDays(v)
	})
}

// UpdatePeriodDays sets the "period_days" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdatePeriodDays() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdatePeriodDays()
	})
}

// SetCurrency sets the "currency" field.
func (u *AccountCostConfigUpsertBulk) SetCurrency(v string) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdateCurrency() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateCurrency()
	})
}

// SetWindowBaselineRevenue sets the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsertBulk) SetWindowBaselineRevenue(v float64) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetWindowBaselineRevenue(v)
	})
}

// AddWindowBaselineRevenue adds v to the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsertBulk) AddWindowBaselineRevenue(v float64) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.AddWindowBaselineRevenue(v)
	})
}

// UpdateWindowBaselineRevenue sets the "window_baseline_revenue" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdateWindowBaselineRevenue() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateWindowBaselineRevenue()
	})
}

// ClearWindowBaselineRevenue clears the value of the "window_baseline_revenue" field.
func (u *AccountCostConfigUpsertBulk) ClearWindowBaselineRevenue() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.ClearWindowBaselineRevenue()
	})
}

// SetNotes sets the "notes" field.
func (u *AccountCostConfigUpsertBulk) SetNotes(v string) *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AccountCostConfigUpsertBulk) UpdateNotes() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AccountCostConfigUpsertBulk) ClearNotes() *AccountCostConfigUpsertBulk {
	return u.Update(func(s *AccountCostConfigUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *AccountCostConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCostConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCostConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountCostConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
