// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcostconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCostConfigDelete is the builder for deleting a AccountCostConfig entity.
type AccountCostConfigDelete struct {
	config
	hooks    []Hook
	mutation *AccountCostConfigMutation
}

// Where appends a list predicates to the AccountCostConfigDelete builder.
func (_d *AccountCostConfigDelete) Where(ps ...predicate.AccountCostConfig) *AccountCostConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountCostConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountCostConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountCostConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountcostconfig.Table, sqlgraph.NewFieldSpec(accountcostconfig.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountCostConfigDeleteOne is the builder for deleting a single AccountCostConfig entity.
type AccountCostConfigDeleteOne struct {
	_d *AccountCostConfigDelete
}

// Where appends a list predicates to the AccountCostConfigDelete builder.
func (_d *AccountCostConfigDeleteOne) Where(ps ...predicate.AccountCostConfig) *AccountCostConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountCostConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountcostconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountCostConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
