<template>
  <component
    :is="iconComponent"
    :class="['shrink-0', sizeClass]"
    :style="strokeStyle"
    aria-hidden="true"
  />
</template>

<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  AcademicCapIcon,
  ArchiveBoxIcon,
  ArrowsPointingOutIcon,
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingUpIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  Bars3Icon,
  BarsArrowUpIcon,
  BeakerIcon,
  BellIcon,
  BoltIcon,
  BookOpenIcon,
  CalculatorIcon,
  CalendarIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  ChatBubbleLeftEllipsisIcon,
  ChatBubbleLeftRightIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentIcon,
  ClipboardIcon,
  ClockIcon,
  CloudIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DocumentTextIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FireIcon,
  FunnelIcon,
  GiftIcon,
  GlobeAltIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyIcon,
  LightBulbIcon,
  LinkIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  NoSymbolIcon,
  PencilSquareIcon,
  PlayIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  ServerIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Squares2X2Icon,
  SunIcon,
  TrashIcon,
  UserCircleIcon,
  UserPlusIcon,
  UserIcon,
  UsersIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/vue/24/outline'

const iconMap = {
  play: PlayIcon,
  refresh: ArrowPathIcon,
  edit: PencilSquareIcon,
  trash: TrashIcon,
  plus: PlusIcon,
  search: MagnifyingGlassIcon,
  more: EllipsisHorizontalIcon,
  chart: ChartBarSquareIcon,
  clock: ClockIcon,
  link: LinkIcon,
  sync: ArrowPathIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  chevronLeft: ChevronLeftIcon,
  check: CheckIcon,
  x: XMarkIcon,
  eye: EyeIcon,
  eyeOff: EyeSlashIcon,
  cog: Cog6ToothIcon,
  grid: Squares2X2Icon,
  chat: ChatBubbleLeftEllipsisIcon,
  lightbulb: LightBulbIcon,
  arrowRight: ArrowRightIcon,
  arrowLeft: ArrowLeftIcon,
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  arrowsUpDown: ArrowsUpDownIcon,
  chevronUp: ChevronUpIcon,
  externalLink: ArrowTopRightOnSquareIcon,
  checkCircle: CheckCircleIcon,
  xCircle: XCircleIcon,
  exclamationCircle: ExclamationCircleIcon,
  exclamationTriangle: ExclamationTriangleIcon,
  infoCircle: InformationCircleIcon,
  questionCircle: QuestionMarkCircleIcon,
  user: UserIcon,
  userCircle: UserCircleIcon,
  userPlus: UserPlusIcon,
  users: UsersIcon,
  document: DocumentTextIcon,
  clipboard: ClipboardIcon,
  copy: ClipboardDocumentIcon,
  inbox: InboxIcon,
  download: ArrowDownTrayIcon,
  upload: ArrowUpTrayIcon,
  filter: FunnelIcon,
  globe: GlobeAltIcon,
  sort: BarsArrowUpIcon,
  key: KeyIcon,
  lock: LockClosedIcon,
  shield: ShieldCheckIcon,
  menu: Bars3Icon,
  calendar: CalendarIcon,
  home: HomeIcon,
  terminal: CommandLineIcon,
  gift: GiftIcon,
  creditCard: CreditCardIcon,
  mail: EnvelopeIcon,
  chartBar: ChartBarIcon,
  trendingUp: ArrowTrendingUpIcon,
  database: CircleStackIcon,
  cube: CubeIcon,
  bell: BellIcon,
  bolt: BoltIcon,
  sparkles: SparklesIcon,
  cloud: CloudIcon,
  server: ServerIcon,
  sun: SunIcon,
  moon: MoonIcon,
  book: BookOpenIcon,
  dollar: CurrencyDollarIcon,
  ban: NoSymbolIcon,
  login: ArrowRightEndOnRectangleIcon,
  swap: ArrowsRightLeftIcon,
  beaker: BeakerIcon,
  cpu: CpuChipIcon,
  chatBubble: ChatBubbleLeftRightIcon,
  calculator: CalculatorIcon,
  fire: FireIcon,
  badge: CheckBadgeIcon,
  brain: AcademicCapIcon,
  logout: ArrowLeftEndOnRectangleIcon,
  archive: ArchiveBoxIcon,
  expand: ArrowsPointingOutIcon,
} as const

export type IconName = keyof typeof iconMap

const props = withDefaults(defineProps<{
  name: IconName
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  strokeWidth?: number
}>(), {
  size: 'md',
  strokeWidth: 1.5,
})

const iconComponent = computed<Component>(() => iconMap[props.name] ?? QuestionMarkCircleIcon)

const sizeClass = computed(() => ({
  xs: 'h-3.5 w-3.5',
  sm: 'h-4 w-4',
  md: 'h-5 w-5',
  lg: 'h-6 w-6',
  xl: 'h-8 w-8',
}[props.size]))

const strokeStyle = computed(() => ({
  strokeWidth: props.strokeWidth,
}))
</script>
